Club Pages (all clubs, club pages)
varangill/ClubHub pull request #10
Opened 2024-01-07 02:21 UTC by Jchuang7

Added dynamic routing to each club page, test functionalities since there's no data to test yet.

2024-01-08 01:55 UTC, varangill requested changes
Comment on the createUL function, let us know if you need help

Also could you post an image in the PR itself for each page that's created/updated in the PR?

2024-01-08 01:55 UTC, varangill commented on client/src/App.tsx
> +function createUL(listItems: Listitem[]): void {
React has custom ways to create a component for objects within an array by calling `map` on the array that we should use, it's a lot cleaner and avoids raw JS DOM manipulation. @kravich2 's [recent PR here](https://github.com/varangill/ClubHub/pull/9/files#diff-26cee6f83578cbe23a73e0f3c317f0764a2a250bc18cc362c69436f42c804730R67) has an example of it

2024-01-08 01:55 UTC, varangill commented on client/src/Club.css
> +    padding: 10px; /* Add padding to the entire header */
Not a blocker but we don't really need comments on CSS properties (unless it's something really weird/confusing), you don't have to remove them here, just a head's up for the future to save some time

2024-01-08 01:55 UTC, varangill commented on client/src/App.tsx
> +function createUL(listItems: Listitem[]): void {
Also this sort of page-specific logic shouldn't be in `App.tsx`

2024-01-09 18:51 UTC, Jchuang7 commented
<img width="1114" alt="image" src="https://github.com/varangill/ClubHub/assets/99681830/9c4ac817-2514-48d7-a10c-d35fe743198c">
<img width="1619" alt="Screen Shot 2024-01-09 at 1 49 07 PM" src="https://github.com/varangill/ClubHub/assets/99681830/2b510fc9-9a9b-4ac9-a5c8-e326ae4022f4">
<img width="962" alt="image" src="https://github.com/varangill/ClubHub/assets/99681830/4ab7adc4-eaf8-40e6-91a0-b1472cb5e15f">
<img width="1620" alt="image" src="https://github.com/varangill/ClubHub/assets/99681830/e5960224-70eb-4365-af3a-7ee4300086f2">

I didn't set up example data yet so the information for members and announcments are the same for now.

2024-03-19 15:36 UTC, closed without merging